apiVersion: v2
type: application
name: external-ingress-auth-service
description: |
  Installs an instance of the External Ingress Authentication Service that provides external authentication for Kubernetes Ingress Controllers.
  It works perfect with NGINX ingress controller via [External Authentication](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#external-authentication).

version: 0.4.0
appVersion: "0.4.0"
keywords:
- authentication
- authorization
- ldap
- htpasswd
- ingress
home: https://argelbargel.github.io/external-ingress-auth/
sources:
- https://github.com/Argelbargel/external-ingress-auth/
maintainers:
- name: Argelbargel
  url: https://github.com/Argelbargel
annotations:
  artifacthub.io/images: |
    - name: external-ingress-auth
      image: ghcr.io/argelbargel/external-ingress-auth:0.3.2
  artifacthub.io/recommendations: |
    - url: https://kubernetes.github.io/ingress-nginx
